/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

/**
 *
 * @author Raynard
 */
public class UserJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserJFrame.class.getName());

    /**
     * Creates new form UserJFrame
     */
    public UserJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        namaLengkapLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        namaLengkapField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        noTelpField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        infoAcaraLabel = new javax.swing.JLabel();
        tanggalAcaraLabel = new javax.swing.JLabel();
        lokasiAcaraLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        pilihMenuLabel = new javax.swing.JLabel();
        pilihPaketLabel = new javax.swing.JLabel();
        jumlahLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        pesananLabel = new javax.swing.JLabel();
        dpLabel = new javax.swing.JLabel();
        metodePembayaranLabel = new javax.swing.JLabel();
        tanggalSpinner = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 215, 196));

        usernameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel1.setFont(new java.awt.Font("Coustard", 1, 24)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(76, 61, 25));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel1.setText("Halo, User!");

        jButton1.setBackground(new java.awt.Color(53, 64, 36));
        jButton1.setFont(new java.awt.Font("Coustard", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 215, 196));
        jButton1.setText("Logout");

        jTabbedPane1.setBackground(new java.awt.Color(162, 154, 124));
        jTabbedPane1.setForeground(new java.awt.Color(76, 61, 25));

        jPanel2.setBackground(new java.awt.Color(162, 154, 124));

        namaLengkapLabel.setFont(new java.awt.Font("Coustard", 0, 14)); // NOI18N
        namaLengkapLabel.setForeground(new java.awt.Color(76, 61, 25));
        namaLengkapLabel.setText("Nama Lengkap :");

        usernameLabel.setFont(new java.awt.Font("Coustard", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(76, 61, 25));
        usernameLabel.setText("Username           :");

        passwordLabel.setFont(new java.awt.Font("Coustard", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(76, 61, 25));
        passwordLabel.setText("Password            :");

        noTelpLabel.setFont(new java.awt.Font("Coustard", 0, 14)); // NOI18N
        noTelpLabel.setForeground(new java.awt.Color(76, 61, 25));
        noTelpLabel.setText("No. Telepon        :");

        alamatLabel.setFont(new java.awt.Font("Coustard", 0, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(76, 61, 25));
        alamatLabel.setText("Alamat                 :");

        namaLengkapField.setBackground(new java.awt.Color(229, 215, 196));

        usernameField.setBackground(new java.awt.Color(229, 215, 196));

        passwordField.setBackground(new java.awt.Color(229, 215, 196));

        noTelpField.setBackground(new java.awt.Color(229, 215, 196));

        alamatTextArea.setBackground(new java.awt.Color(229, 215, 196));
        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        jButton2.setBackground(new java.awt.Color(53, 64, 36));
        jButton2.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(229, 215, 196));
        jButton2.setText("Update");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(namaLengkapLabel)
                        .addGap(18, 18, 18)
                        .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(noTelpLabel)
                            .addComponent(alamatLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLengkapLabel)
                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLabel)
                    .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profil Saya", jPanel2);

        jPanel3.setBackground(new java.awt.Color(162, 154, 124));

        infoAcaraLabel.setFont(new java.awt.Font("Coustard", 1, 14)); // NOI18N
        infoAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        infoAcaraLabel.setText("Bagian 1 : Info Acara");

        tanggalAcaraLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        tanggalAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        tanggalAcaraLabel.setText("Tanggal acara :");

        lokasiAcaraLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        lokasiAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        lokasiAcaraLabel.setText("Lokasi acara :");

        catatanLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        catatanLabel.setForeground(new java.awt.Color(76, 61, 25));
        catatanLabel.setText("Catatan :");

        pilihMenuLabel.setFont(new java.awt.Font("Coustard", 1, 14)); // NOI18N
        pilihMenuLabel.setForeground(new java.awt.Color(76, 61, 25));
        pilihMenuLabel.setText("Bagian 2 : Pilih Menu");

        pilihPaketLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        pilihPaketLabel.setForeground(new java.awt.Color(76, 61, 25));
        pilihPaketLabel.setText("Pilih paket menu :");

        jumlahLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        jumlahLabel.setForeground(new java.awt.Color(76, 61, 25));
        jumlahLabel.setText("Jumlah (porsi) :");

        totalHargaLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(76, 61, 25));
        totalHargaLabel.setText("Total harga : Rp");

        pesananLabel.setFont(new java.awt.Font("Coustard", 1, 14)); // NOI18N
        pesananLabel.setForeground(new java.awt.Color(76, 61, 25));
        pesananLabel.setText("Bagian 3 : Pesanan");

        dpLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        dpLabel.setForeground(new java.awt.Color(76, 61, 25));
        dpLabel.setText("DP (50%) : Rp");

        metodePembayaranLabel.setFont(new java.awt.Font("Coustard", 0, 12)); // NOI18N
        metodePembayaranLabel.setForeground(new java.awt.Color(76, 61, 25));
        metodePembayaranLabel.setText("Metode Pembayaran :");

        tanggalSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        tanggalSpinner.setEditor(new javax.swing.JSpinner.DateEditor(tanggalSpinner, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoAcaraLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tanggalAcaraLabel)
                                .addGap(18, 18, 18)
                                .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pilihMenuLabel)
                            .addComponent(pilihPaketLabel)
                            .addComponent(jumlahLabel)
                            .addComponent(pesananLabel))
                        .addContainerGap(370, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metodePembayaranLabel)
                            .addComponent(dpLabel)
                            .addComponent(totalHargaLabel)
                            .addComponent(catatanLabel)
                            .addComponent(lokasiAcaraLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(infoAcaraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalAcaraLabel)
                    .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lokasiAcaraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatanLabel)
                .addGap(24, 24, 24)
                .addComponent(pilihMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihPaketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahLabel)
                .addGap(27, 27, 27)
                .addComponent(pesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHargaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodePembayaranLabel)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buat Pesanan", jPanel3);

        jPanel4.setBackground(new java.awt.Color(162, 154, 124));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Katalog Menu", jPanel4);

        jPanel5.setBackground(new java.awt.Color(162, 154, 124));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Riwayat Pesanan", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(usernameLabel1))
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JLabel dpLabel;
    private javax.swing.JLabel infoAcaraLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JLabel lokasiAcaraLabel;
    private javax.swing.JLabel metodePembayaranLabel;
    private javax.swing.JTextField namaLengkapField;
    private javax.swing.JLabel namaLengkapLabel;
    private javax.swing.JTextField noTelpField;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pesananLabel;
    private javax.swing.JLabel pilihMenuLabel;
    private javax.swing.JLabel pilihPaketLabel;
    private javax.swing.JLabel tanggalAcaraLabel;
    private javax.swing.JSpinner tanggalSpinner;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
