/*
* Nama Program : NyamBeans
* Nama         : Vincentius Raynard Thedy, Nena Haryadi Puspanegara, Alfon Daren Witanto
* NPM          : 140810240028, 140810240034, 140810240052
* Tanggal buat : 28 November - 4 Desember 2025
* Deskripsi    : UserJFrame.java (JFrame class)
*/

package User;

import Model.DetailPesanan;
import Model.Menu;
import Model.Pesanan;
import Model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Raynard
 */
public class UserJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserJFrame.class.getName());
    
    private User currentUser;
    private List<DetailPesanan> keranjangBelanja; // Menyimpan item sementara
    private int grandTotal = 0;
    
    public UserJFrame() {
        initComponents();
    }
    
    // Constructor Utama 
    public UserJFrame(User user) {
        initComponents();
        this.currentUser = user;
        this.keranjangBelanja = new ArrayList<>();
        
        initUserData();
        loadKatalogMenu();
        loadRiwayatPesanan();
    }
    
    private void loadKatalogMenu() {
        DefaultTableModel model = (DefaultTableModel) tabelMenu.getModel();
        model.setRowCount(0);
        List<Menu> menus = Menu.getAllMenu();
        for (Menu m : menus) {
            model.addRow(new Object[]{ m.getNamaMenu(), m.getJenisMenu(), m.getHargaPerPorsi(), m.getDeskripsi() });
        }
    }
    
    private void loadRiwayatPesanan() {
        if (currentUser == null) return;
        DefaultTableModel model = (DefaultTableModel) tabelRiwayatPesanan.getModel();
        model.setRowCount(0);
        List<Pesanan> list = Pesanan.getRiwayatUser(currentUser.getIdUser());
        for (Pesanan p : list) {
            model.addRow(new Object[]{ p.getTglAcara(), "Lihat Detail", p.getTotalHarga(), p.getStatus() });
        }
    }
    
    private void refreshTabelKeranjang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        grandTotal = 0;
        
        for (DetailPesanan d : keranjangBelanja) {
            model.addRow(new Object[]{
                d.getNamaMenu(),
                d.getHargaSatuan(),
                d.getJumlahPorsi(),
                d.getSubtotal()
            });
            grandTotal += d.getSubtotal();
        }
        
        totalField.setText(String.valueOf(grandTotal));
        int dp = grandTotal / 2;
        dpField.setText(String.valueOf(dp));
    }
    
    private void initUserData() {
        if (currentUser != null) {
            usernameLabel1.setText("Halo, " + currentUser.getNama() + "!");
            
            // Tab Profil
            namaLengkapField.setText(currentUser.getNama());
            usernameField.setText(currentUser.getUsername());
            // Password tidak ditampilkan demi keamanan
            noTelpField.setText(currentUser.getNoTelp());
            emailField.setText(currentUser.getEmail());
            alamatTextArea.setText(currentUser.getAlamat());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        namaLengkapLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        namaLengkapField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        noTelpField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        showPassCheck = new javax.swing.JCheckBox();
        passwordField = new javax.swing.JPasswordField();
        copyright5 = new javax.swing.JLabel();
        copyright12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        infoAcaraLabel = new javax.swing.JLabel();
        tanggalAcaraLabel = new javax.swing.JLabel();
        lokasiAcaraLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        pilihMenuLabel = new javax.swing.JLabel();
        pilihPaketLabel = new javax.swing.JLabel();
        jumlahLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        pesananLabel = new javax.swing.JLabel();
        dpLabel = new javax.swing.JLabel();
        metodePembayaranLabel = new javax.swing.JLabel();
        tanggalSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        lokasiText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        catatanText = new javax.swing.JTextArea();
        menuField = new javax.swing.JTextField();
        jmlPorsiSpiner = new javax.swing.JSpinner();
        totalField = new javax.swing.JTextField();
        dpField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambahkanBtn = new javax.swing.JButton();
        hapusItemBtn = new javax.swing.JButton();
        PesanBtn = new javax.swing.JButton();
        copyright6 = new javax.swing.JLabel();
        copyright11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelMenu = new javax.swing.JTable();
        copyright7 = new javax.swing.JLabel();
        copyright10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelRiwayatPesanan = new javax.swing.JTable();
        copyright8 = new javax.swing.JLabel();
        copyright9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 215, 196));

        usernameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(76, 61, 25));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel1.setText("Halo, User!");

        logoutButton.setBackground(new java.awt.Color(53, 64, 36));
        logoutButton.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(229, 215, 196));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(162, 154, 124));
        jTabbedPane1.setForeground(new java.awt.Color(76, 61, 25));

        jPanel2.setBackground(new java.awt.Color(162, 154, 124));

        namaLengkapLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        namaLengkapLabel.setForeground(new java.awt.Color(76, 61, 25));
        namaLengkapLabel.setText("Nama Lengkap :");

        usernameLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(76, 61, 25));
        usernameLabel.setText("Username           :");

        passwordLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(76, 61, 25));
        passwordLabel.setText("Password            :");

        noTelpLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        noTelpLabel.setForeground(new java.awt.Color(76, 61, 25));
        noTelpLabel.setText("No. Telepon        :");

        alamatLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(76, 61, 25));
        alamatLabel.setText("Alamat                 :");

        namaLengkapField.setBackground(new java.awt.Color(229, 215, 196));
        namaLengkapField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        namaLengkapField.setForeground(new java.awt.Color(76, 61, 25));
        namaLengkapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapFieldActionPerformed(evt);
            }
        });

        usernameField.setBackground(new java.awt.Color(229, 215, 196));
        usernameField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        usernameField.setForeground(new java.awt.Color(76, 61, 25));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        noTelpField.setBackground(new java.awt.Color(229, 215, 196));
        noTelpField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        noTelpField.setForeground(new java.awt.Color(76, 61, 25));
        noTelpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpFieldActionPerformed(evt);
            }
        });

        alamatTextArea.setBackground(new java.awt.Color(229, 215, 196));
        alamatTextArea.setColumns(20);
        alamatTextArea.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        alamatTextArea.setForeground(new java.awt.Color(76, 61, 25));
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        updateButton.setBackground(new java.awt.Color(53, 64, 36));
        updateButton.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(229, 215, 196));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        emailField.setBackground(new java.awt.Color(229, 215, 196));
        emailField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(76, 61, 25));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(76, 61, 25));
        emailLabel.setText("Email                   :");

        showPassCheck.setText("Lihat");
        showPassCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCheckActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(229, 215, 196));
        passwordField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(76, 61, 25));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        copyright5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright5.setForeground(new java.awt.Color(76, 61, 25));
        copyright5.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        copyright12.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        copyright12.setForeground(new java.awt.Color(76, 61, 25));
        copyright12.setText("CP : 081024283452");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noTelpLabel)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLengkapLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(noTelpField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(copyright5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright12)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLengkapLabel)
                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(showPassCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLabel)
                    .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyright5)
                    .addComponent(copyright12))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Profil Saya", jPanel2);

        jPanel3.setBackground(new java.awt.Color(162, 154, 124));

        infoAcaraLabel.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        infoAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        infoAcaraLabel.setText("Bagian 1 : Info Acara");

        tanggalAcaraLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tanggalAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        tanggalAcaraLabel.setText("Tanggal acara :");

        lokasiAcaraLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        lokasiAcaraLabel.setForeground(new java.awt.Color(76, 61, 25));
        lokasiAcaraLabel.setText("Lokasi acara   :");

        catatanLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        catatanLabel.setForeground(new java.awt.Color(76, 61, 25));
        catatanLabel.setText("Catatan          :");

        pilihMenuLabel.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        pilihMenuLabel.setForeground(new java.awt.Color(76, 61, 25));
        pilihMenuLabel.setText("Bagian 2 : Pilih Menu");

        pilihPaketLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        pilihPaketLabel.setForeground(new java.awt.Color(76, 61, 25));
        pilihPaketLabel.setText("Pilih menu       :");

        jumlahLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jumlahLabel.setForeground(new java.awt.Color(76, 61, 25));
        jumlahLabel.setText("Jumlah (porsi) :");

        totalHargaLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(76, 61, 25));
        totalHargaLabel.setText("Total harga               :  Rp");

        pesananLabel.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        pesananLabel.setForeground(new java.awt.Color(76, 61, 25));
        pesananLabel.setText("Bagian 3 : Pesanan");

        dpLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        dpLabel.setForeground(new java.awt.Color(76, 61, 25));
        dpLabel.setText("DP (50%)                  :  Rp");

        metodePembayaranLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        metodePembayaranLabel.setForeground(new java.awt.Color(76, 61, 25));
        metodePembayaranLabel.setText("Metode Pembayaran :");

        tanggalSpinner.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tanggalSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        tanggalSpinner.setEditor(new javax.swing.JSpinner.DateEditor(tanggalSpinner, "dd/MM/yyyy"));

        lokasiText.setBackground(new java.awt.Color(229, 215, 196));
        lokasiText.setColumns(20);
        lokasiText.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        lokasiText.setForeground(new java.awt.Color(76, 61, 25));
        lokasiText.setRows(5);
        jScrollPane2.setViewportView(lokasiText);

        catatanText.setBackground(new java.awt.Color(229, 215, 196));
        catatanText.setColumns(20);
        catatanText.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        catatanText.setForeground(new java.awt.Color(76, 61, 25));
        catatanText.setRows(5);
        jScrollPane3.setViewportView(catatanText);

        menuField.setBackground(new java.awt.Color(229, 215, 196));
        menuField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        menuField.setForeground(new java.awt.Color(76, 61, 25));

        jmlPorsiSpiner.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N

        totalField.setEditable(false);
        totalField.setBackground(new java.awt.Color(229, 215, 196));
        totalField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalField.setForeground(new java.awt.Color(76, 61, 25));

        dpField.setEditable(false);
        dpField.setBackground(new java.awt.Color(229, 215, 196));
        dpField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        dpField.setForeground(new java.awt.Color(76, 61, 25));

        jComboBox1.setBackground(new java.awt.Color(229, 215, 196));
        jComboBox1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(76, 61, 25));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Transfer" }));

        jTable1.setBackground(new java.awt.Color(229, 215, 196));
        jTable1.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(76, 61, 25));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Menu", "Harga/porsi", "Jumlah", "Subtotal"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        tambahkanBtn.setBackground(new java.awt.Color(53, 64, 36));
        tambahkanBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tambahkanBtn.setForeground(new java.awt.Color(229, 215, 196));
        tambahkanBtn.setText("+ Tambahkan");
        tambahkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanBtnActionPerformed(evt);
            }
        });

        hapusItemBtn.setBackground(new java.awt.Color(134, 15, 15));
        hapusItemBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        hapusItemBtn.setForeground(new java.awt.Color(229, 215, 196));
        hapusItemBtn.setText("Hapus Item");
        hapusItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusItemBtnActionPerformed(evt);
            }
        });

        PesanBtn.setBackground(new java.awt.Color(54, 64, 36));
        PesanBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        PesanBtn.setForeground(new java.awt.Color(229, 215, 196));
        PesanBtn.setText("Pesan Sekarang");
        PesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanBtnActionPerformed(evt);
            }
        });

        copyright6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright6.setForeground(new java.awt.Color(76, 61, 25));
        copyright6.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        copyright11.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        copyright11.setForeground(new java.awt.Color(76, 61, 25));
        copyright11.setText("CP : 081024283452");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyright6)
                            .addComponent(pilihMenuLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jumlahLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jmlPorsiSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pilihPaketLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tambahkanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pesananLabel)
                            .addComponent(infoAcaraLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(catatanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggalAcaraLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lokasiAcaraLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(totalHargaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(metodePembayaranLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dpField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97)
                                .addComponent(PesanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapusItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(copyright11)
                                .addGap(22, 22, 22))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(infoAcaraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggalAcaraLabel)
                    .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lokasiAcaraLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pilihMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihPaketLabel)
                    .addComponent(menuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahkanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahLabel)
                    .addComponent(jmlPorsiSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pesananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHargaLabel)
                            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dpLabel)
                            .addComponent(dpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(metodePembayaranLabel)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PesanBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyright6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hapusItemBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyright11)
                        .addGap(15, 15, 15))))
        );

        jTabbedPane1.addTab("Buat Pesanan", jPanel3);

        jPanel4.setBackground(new java.awt.Color(162, 154, 124));

        tabelMenu.setBackground(new java.awt.Color(229, 215, 196));
        tabelMenu.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tabelMenu.setForeground(new java.awt.Color(76, 61, 25));
        tabelMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Menu", "Jenis Menu", "Harga/porsi", "Deskripsi"
            }
        ));
        tabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMenuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelMenu);

        copyright7.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright7.setForeground(new java.awt.Color(76, 61, 25));
        copyright7.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        copyright10.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        copyright10.setForeground(new java.awt.Color(76, 61, 25));
        copyright10.setText("CP : 081024283452");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(copyright7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyright10)
                        .addGap(25, 25, 25))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyright7)
                    .addComponent(copyright10))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Katalog Menu", jPanel4);

        jPanel5.setBackground(new java.awt.Color(162, 154, 124));

        tabelRiwayatPesanan.setBackground(new java.awt.Color(229, 215, 196));
        tabelRiwayatPesanan.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tabelRiwayatPesanan.setForeground(new java.awt.Color(76, 61, 25));
        tabelRiwayatPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal Acara", "Menu", "Total harga", "Status"
            }
        ));
        tabelRiwayatPesanan.setEnabled(false);
        jScrollPane6.setViewportView(tabelRiwayatPesanan);

        copyright8.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright8.setForeground(new java.awt.Color(76, 61, 25));
        copyright8.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        copyright9.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        copyright9.setForeground(new java.awt.Color(76, 61, 25));
        copyright9.setText("CP : 081024283452");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(copyright8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyright9)
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(copyright8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(copyright9)
                        .addGap(17, 17, 17))))
        );

        jTabbedPane1.addTab("Riwayat Pesanan", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(usernameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusItemBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            keranjangBelanja.remove(row);
            refreshTabelKeranjang();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih item yang mau dihapus!");
        }
    }

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        passwordField.requestFocus();
    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentUser == null) return;
        // ambil data dari form
        String nama = namaLengkapField.getText().trim();
        String username = usernameField.getText().trim();
        String noTelp = noTelpField.getText().trim();
        String email = emailField.getText().trim();
        String alamat = alamatTextArea.getText().trim();
        String pass = new String(passwordField.getPassword()).trim(); 
        
        if (nama.isEmpty() || username.isEmpty() || noTelp.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama, Username, No. Telp, dan Email wajib diisi!");
            return;
        }
        
        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "No. Telepon harus berupa angka!");
            return;
        }
        
        // validasi Email ada @, tidak di awal/akhir
        if (!email.contains("@") || email.startsWith("@") || email.endsWith("@")) {
            JOptionPane.showMessageDialog(this, "Format Email tidak valid!");
            return;
        }
        
        // validasi password hanya jika diisi
        if (!pass.isEmpty()) {
            if (pass.length() < 6 || pass.length() > 8) {
                JOptionPane.showMessageDialog(this, 
                    "Password baru harus 6 sampai 8 karakter!", 
                    "Password Tidak Valid", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            currentUser.setPassword(pass);
        }
        
        // set data lain ke objek User
        currentUser.setNama(nama);
        currentUser.setUsername(username);
        currentUser.setNoTelp(noTelp);
        currentUser.setEmail(email);
        currentUser.setAlamat(alamat);

        if (currentUser.updateUser()) {
            JOptionPane.showMessageDialog(this, "Profil Berhasil Diupdate!");

            usernameLabel1.setText("Halo, " + currentUser.getNama() + "!");
            
            passwordField.setText(""); 
        } else {
            JOptionPane.showMessageDialog(this, "Gagal update profil. Cek koneksi atau username mungkin sudah dipakai.");
        }
    }

    private void tambahkanBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String namaMenu = menuField.getText();
        int qty = (int) jmlPorsiSpiner.getValue();
        
        if (qty <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah porsi minimal 1!");
            return;
        }
        
        Menu m = Menu.getMenuByName(namaMenu);
        if (m != null) {
            DetailPesanan detail = new DetailPesanan(m.getIdMenu(), m.getNamaMenu(), qty, m.getHargaPerPorsi());
            keranjangBelanja.add(detail);
            refreshTabelKeranjang();
            menuField.setText(""); // reset field
            jmlPorsiSpiner.setValue(0);
        } else {
            JOptionPane.showMessageDialog(this, "Menu tidak ditemukan! Cek ejaan di Katalog.");
        }
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void PesanBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (keranjangBelanja.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong!");
            return;
        }
        
        String lokasi = lokasiText.getText();
        String catatan = catatanText.getText(); // ambil catatan
        Date tglAcara = (Date) tanggalSpinner.getValue();
        String metode = jComboBox1.getSelectedItem().toString(); // ambil metode bayar
        
        if (lokasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lokasi acara harus diisi!");
            return;
        }
        
        Pesanan p = new Pesanan();
        p.setIdUser(currentUser.getIdUser());
        p.setTglAcara(new java.sql.Date(tglAcara.getTime()));
        p.setLokasiAcara(lokasi); 
        p.setCatatan(catatan);      
        p.setMetodeBayar(metode);   
        p.setTotalHarga(grandTotal);
        
        if (p.simpanPesanan(keranjangBelanja)) {
            JOptionPane.showMessageDialog(this, "Pesanan Berhasil Dibuat! Silakan bayar DP.");
            keranjangBelanja.clear();
            refreshTabelKeranjang();
            lokasiText.setText("");
            catatanText.setText("");
            loadRiwayatPesanan(); 
            jTabbedPane1.setSelectedIndex(3); // pindah ke tab Riwayat
        } else {
            JOptionPane.showMessageDialog(this, "Gagal membuat pesanan. Cek koneksi database.");
        }
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new Auth.LoginJFrame().setVisible(true);
    }

    private void tabelMenuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tabelMenu.getSelectedRow();
        if (row >= 0) {
            String namaMenu = tabelMenu.getValueAt(row, 0).toString();
            jTabbedPane1.setSelectedIndex(1);
            menuField.setText(namaMenu);
        }
    }

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        alamatTextArea.requestFocus();
    }

    private void showPassCheckActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (showPassCheck.isSelected()) {
            passwordField.setEchoChar((char) 0);
        } else {
            passwordField.setEchoChar('*');
        }
    }

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        noTelpField.requestFocus();
    }

    private void namaLengkapFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        usernameField.requestFocus();
    }

    private void noTelpFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        emailField.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new UserJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PesanBtn;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextArea catatanText;
    private javax.swing.JLabel copyright10;
    private javax.swing.JLabel copyright11;
    private javax.swing.JLabel copyright12;
    private javax.swing.JLabel copyright5;
    private javax.swing.JLabel copyright6;
    private javax.swing.JLabel copyright7;
    private javax.swing.JLabel copyright8;
    private javax.swing.JLabel copyright9;
    private javax.swing.JTextField dpField;
    private javax.swing.JLabel dpLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton hapusItemBtn;
    private javax.swing.JLabel infoAcaraLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner jmlPorsiSpiner;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel lokasiAcaraLabel;
    private javax.swing.JTextArea lokasiText;
    private javax.swing.JTextField menuField;
    private javax.swing.JLabel metodePembayaranLabel;
    private javax.swing.JTextField namaLengkapField;
    private javax.swing.JLabel namaLengkapLabel;
    private javax.swing.JTextField noTelpField;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pesananLabel;
    private javax.swing.JLabel pilihMenuLabel;
    private javax.swing.JLabel pilihPaketLabel;
    private javax.swing.JCheckBox showPassCheck;
    private javax.swing.JTable tabelMenu;
    private javax.swing.JTable tabelRiwayatPesanan;
    private javax.swing.JButton tambahkanBtn;
    private javax.swing.JLabel tanggalAcaraLabel;
    private javax.swing.JSpinner tanggalSpinner;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
