/*
* Nama Program : NyamBeans
* Nama         : Vincentius Raynard Thedy, Nena Haryadi Puspanegara, Alfon Daren Witanto
* NPM          : 140810240028, 140810240034, 140810240052
* Tanggal buat : 28 November - 4 Desember 2025
* Deskripsi    : DetailUserJDialog.java (JDialog class)
*/

package Admin;

import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Raynard
 */
public class DetailUserJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailUserJDialog.class.getName());
    private int userId = 0;
    
    public DetailUserJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tambah User Baru");
        
        this.userId = 0;
    }
    
    public DetailUserJDialog(java.awt.Frame parent, boolean modal, int idUserToEdit) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        this.userId = idUserToEdit;
        setTitle("Edit Data User");
        loadUserData(this.userId);
    }
    
    // Method untuk mengisi form saat Mode Edit
    private void loadUserData(int id) {
        for (User u : User.getAllUsers()) {
            if (u.getIdUser() == id) {
                namaLengkapField.setText(u.getNama());
                usernameField.setText(u.getUsername());
                rolePenggunaComboBox.setSelectedItem(u.getRole());
                noTelpField.setText(u.getNoTelp());
                emailField.setText(u.getEmail());
                alamatTextArea.setText(u.getAlamat());
                return; 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        namaLengkapLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        noTelpLabel = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        alamatLabel = new javax.swing.JLabel();
        rolePenggunaComboBox = new javax.swing.JComboBox<>();
        namaLengkapField = new javax.swing.JTextField();
        detailUserLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        noTelpField = new javax.swing.JTextField();
        batalButton = new javax.swing.JButton();
        showPassCheck = new javax.swing.JCheckBox();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        copyright5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 154, 124));

        alamatTextArea.setBackground(new java.awt.Color(229, 215, 196));
        alamatTextArea.setColumns(20);
        alamatTextArea.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        alamatTextArea.setForeground(new java.awt.Color(76, 61, 25));
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        namaLengkapLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        namaLengkapLabel.setForeground(new java.awt.Color(76, 61, 25));
        namaLengkapLabel.setText("Nama Lengkap :");

        passwordField.setBackground(new java.awt.Color(229, 215, 196));
        passwordField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(76, 61, 25));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(76, 61, 25));
        usernameLabel.setText("Username         :");

        passwordLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(76, 61, 25));
        passwordLabel.setText("Password          :");

        roleLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(76, 61, 25));
        roleLabel.setText("Role                  :");

        noTelpLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        noTelpLabel.setForeground(new java.awt.Color(76, 61, 25));
        noTelpLabel.setText("No. Telepon      :");

        simpanButton.setBackground(new java.awt.Color(53, 64, 36));
        simpanButton.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(229, 215, 196));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        alamatLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(76, 61, 25));
        alamatLabel.setText("Alamat              :");

        rolePenggunaComboBox.setBackground(new java.awt.Color(229, 215, 196));
        rolePenggunaComboBox.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        rolePenggunaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        rolePenggunaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolePenggunaComboBoxActionPerformed(evt);
            }
        });

        namaLengkapField.setBackground(new java.awt.Color(229, 215, 196));
        namaLengkapField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        namaLengkapField.setForeground(new java.awt.Color(76, 61, 25));
        namaLengkapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapFieldActionPerformed(evt);
            }
        });

        detailUserLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        detailUserLabel.setForeground(new java.awt.Color(76, 61, 25));
        detailUserLabel.setText("Detail User");

        usernameField.setBackground(new java.awt.Color(229, 215, 196));
        usernameField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        usernameField.setForeground(new java.awt.Color(76, 61, 25));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        noTelpField.setBackground(new java.awt.Color(229, 215, 196));
        noTelpField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        noTelpField.setForeground(new java.awt.Color(76, 61, 25));
        noTelpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpFieldActionPerformed(evt);
            }
        });

        batalButton.setBackground(new java.awt.Color(134, 15, 15));
        batalButton.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        batalButton.setForeground(new java.awt.Color(229, 215, 196));
        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        showPassCheck.setText("Lihat");
        showPassCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCheckActionPerformed(evt);
            }
        });

        emailField.setBackground(new java.awt.Color(229, 215, 196));
        emailField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(76, 61, 25));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(76, 61, 25));
        emailLabel.setText("Email                :");

        copyright5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright5.setForeground(new java.awt.Color(76, 61, 25));
        copyright5.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyright5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alamatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detailUserLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLengkapLabel)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel)
                                    .addComponent(roleLabel)
                                    .addComponent(noTelpLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rolePenggunaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(detailUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaLengkapLabel)
                    .addComponent(namaLengkapField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPassCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rolePenggunaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noTelpLabel)
                            .addComponent(noTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanButton)
                    .addComponent(batalButton))
                .addGap(18, 18, 18)
                .addComponent(copyright5)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        noTelpField.requestFocus();
    }

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // mengambil data dari form
        String nama = namaLengkapField.getText();
        String username = usernameField.getText();
        String pass = new String(passwordField.getPassword());
        String role = rolePenggunaComboBox.getSelectedItem().toString();
        String telp = noTelpField.getText().trim();
        String email = emailField.getText().trim();
        String alamat = alamatTextArea.getText();

        if (!pass.isEmpty()) {
            if (pass.length() < 6 || pass.length() > 8) {
                JOptionPane.showMessageDialog(this, 
                    "Password harus 6 sampai 8 karakter!", 
                    "Password Tidak Valid", 
                    JOptionPane.WARNING_MESSAGE);
                return; 
            }
        }
        
        if (nama.isEmpty() || username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama dan Username wajib diisi!");
            return;
        }
        
        if (!telp.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "No. Telepon harus berupa angka!");
            return;
        }

        if (!email.contains("@") || email.startsWith("@") || email.endsWith("@")) {
            JOptionPane.showMessageDialog(this, "Format Email tidak valid!");
            return;
        }

        User u = new User();
        u.setNama(nama);
        u.setUsername(username);
        u.setRole(role);
        u.setNoTelp(telp);
        u.setAlamat(alamat);

        if (userId == 0) {
            if (pass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password wajib diisi untuk user baru!");
                return;
            }
            u.setPassword(pass);
            
            if (u.tambahUser()) {
                JOptionPane.showMessageDialog(this, "User Berhasil Ditambahkan!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambah user (Cek duplikat username).");
            }
            
        } else {
            //edit data
            u.setIdUser(userId); 
            if (!pass.isEmpty()) {
                u.setPassword(pass); 
            }
            
            if (u.updateUser()) {
                JOptionPane.showMessageDialog(this, "User Berhasil Diupdate!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal update user.");
            }
        }
    }

    private void rolePenggunaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolePenggunaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolePenggunaComboBoxActionPerformed

    private void namaLengkapFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        usernameField.requestFocus();
    }

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        passwordField.requestFocus();
    }

    private void noTelpFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here
        emailField.requestFocus();
    }

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void showPassCheckActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (showPassCheck.isSelected()) {
            passwordField.setEchoChar((char) 0); 
        } else {
            passwordField.setEchoChar('*'); 
        }
    }

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        alamatTextArea.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DetailUserJDialog dialog = new DetailUserJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JButton batalButton;
    private javax.swing.JLabel copyright5;
    private javax.swing.JLabel detailUserLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaLengkapField;
    private javax.swing.JLabel namaLengkapLabel;
    private javax.swing.JTextField noTelpField;
    private javax.swing.JLabel noTelpLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JComboBox<String> rolePenggunaComboBox;
    private javax.swing.JCheckBox showPassCheck;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
