/*
* Nama Program : NyamBeans
* Nama         : Vincentius Raynard Thedy, Nena Haryadi Puspanegara, Alfon Daren Witanto
* NPM          : 140810240028, 140810240034, 140810240052
* Tanggal buat : 28 November - 4 Desember 2025
* Deskripsi    : DetailPesananJDialog.java (JDialog class)
*/

package Admin;

import Model.DetailPesanan;
import Model.Pesanan;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nenap
 */
public class DetailPesananJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetailPesananJDialog.class.getName());

    /**
     * Creates new form detailUserJDialog
     */
    public DetailPesananJDialog(java.awt.Frame parent, boolean modal, int idPesanan) {
        super(parent, modal);
        initComponents();
        loadData(idPesanan); // Panggil fungsi load data
        setLocationRelativeTo(null); // Agar muncul di tengah layar
    }
    
    // Method Helper: Mengisi Form dan Tabel
    private void loadData(int id) {
        // 1. Isi Data Header (Nama, Status, Total, Catatan)
        Pesanan p = Pesanan.getPesananById(id);
        if (p != null) {
            detailPesananField.setText(p.getNamaPemesan());
            statusField.setText(p.getStatus());
            totalHargaField.setText("Rp " + p.getTotalHarga());
            catatanText.setText(p.getCatatan());
            
            // Matikan edit agar Admin hanya bisa melihat (Read Only)
            detailPesananField.setEditable(false);
            statusField.setEditable(false);
            totalHargaField.setEditable(false);
            catatanText.setEditable(false);
        }

        // 2. Isi Tabel Rincian Menu
        DefaultTableModel model = (DefaultTableModel) daftarMenuDipesanTable.getModel();
        model.setRowCount(0);
        List<DetailPesanan> details = DetailPesanan.getDetailByPesananId(id);
        
        for (DetailPesanan d : details) {
            model.addRow(new Object[]{
                d.getNamaMenu(),
                d.getHargaSatuan(),
                d.getJumlahPorsi(),
                d.getSubtotal()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        detailPesananLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        daftarMenuDipesanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarMenuDipesanTable = new javax.swing.JTable();
        totalHargaLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        detailPesananField = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        totalHargaField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatanText = new javax.swing.JTextArea();
        tutupLabel = new javax.swing.JButton();
        copyright5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(76, 61, 25));

        jPanel1.setBackground(new java.awt.Color(162, 154, 124));

        detailPesananLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        detailPesananLabel.setForeground(new java.awt.Color(76, 61, 25));
        detailPesananLabel.setText("Detail Pesanan  : ");

        statusLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(76, 61, 25));
        statusLabel.setText("Status               :");

        daftarMenuDipesanLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        daftarMenuDipesanLabel.setForeground(new java.awt.Color(76, 61, 25));
        daftarMenuDipesanLabel.setText("Daftar Menu yang Dipesan :");

        daftarMenuDipesanTable.setBackground(new java.awt.Color(229, 215, 196));
        daftarMenuDipesanTable.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        daftarMenuDipesanTable.setForeground(new java.awt.Color(76, 61, 25));
        daftarMenuDipesanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Harga", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(daftarMenuDipesanTable);

        totalHargaLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(76, 61, 25));
        totalHargaLabel.setText("Total Harga :  Rp.");

        catatanLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        catatanLabel.setForeground(new java.awt.Color(76, 61, 25));
        catatanLabel.setText("Catatan       :");

        detailPesananField.setBackground(new java.awt.Color(162, 154, 124));
        detailPesananField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        detailPesananField.setForeground(new java.awt.Color(76, 61, 25));

        statusField.setBackground(new java.awt.Color(162, 154, 124));
        statusField.setForeground(new java.awt.Color(76, 61, 25));

        totalHargaField.setBackground(new java.awt.Color(162, 154, 124));
        totalHargaField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalHargaField.setForeground(new java.awt.Color(76, 61, 25));

        catatanText.setBackground(new java.awt.Color(162, 154, 124));
        catatanText.setColumns(20);
        catatanText.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        catatanText.setForeground(new java.awt.Color(76, 61, 25));
        catatanText.setRows(5);
        jScrollPane2.setViewportView(catatanText);

        tutupLabel.setBackground(new java.awt.Color(53, 64, 36));
        tutupLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tutupLabel.setForeground(new java.awt.Color(229, 215, 196));
        tutupLabel.setText("Tutup");
        tutupLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupLabelActionPerformed(evt);
            }
        });

        copyright5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright5.setForeground(new java.awt.Color(76, 61, 25));
        copyright5.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(copyright5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(catatanLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(tutupLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daftarMenuDipesanLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalHargaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(statusLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(statusField))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(detailPesananLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(detailPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tutupLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailPesananLabel)
                            .addComponent(detailPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLabel)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(daftarMenuDipesanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHargaLabel)
                            .addComponent(totalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catatanLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(copyright5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutupLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupLabelActionPerformed
        this.dispose();
    }//GEN-LAST:event_tutupLabelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextArea catatanText;
    private javax.swing.JLabel copyright5;
    private javax.swing.JLabel daftarMenuDipesanLabel;
    private javax.swing.JTable daftarMenuDipesanTable;
    private javax.swing.JTextField detailPesananField;
    private javax.swing.JLabel detailPesananLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField totalHargaField;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JButton tutupLabel;
    // End of variables declaration//GEN-END:variables
}
