/*
* Nama Program : NyamBeans
* Nama         : Vincentius Raynard Thedy, Nena Haryadi Puspanegara, Alfon Daren Witanto
* NPM          : 140810240028, 140810240034, 140810240052
* Tanggal buat : 28 November - 4 Desember 2025
* Deskripsi    : UpdateStatusBayarJDialog.java (JDialog class)
*/

package Admin;

import Auth.DatabaseConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nenap
 */
public class UpdateStatusBayarJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateStatusBayarJDialog.class.getName());
    
    private int currentIdPesanan;
    private int totalHarga = 0;
    
    public UpdateStatusBayarJDialog(java.awt.Frame parent, boolean modal, int idPesanan) {
        super(parent, modal);
        initComponents();
        this.currentIdPesanan = idPesanan;
        loadData();
        setLocationRelativeTo(null);
    }
    
    private void loadData() {
        // Panggil method statis dari Model
        Model.Pesanan p = Model.Pesanan.getPesananById(currentIdPesanan);

        if (p != null) {
            idPesananField.setText(String.valueOf(p.getIdPesanan()));
            namaPemesanField.setText(p.getNamaPemesan());
            this.totalHarga = p.getTotalHarga(); 
            totalTagihanField.setText(String.valueOf(totalHarga));
            statusPesanan.setSelectedItem(p.getStatus());
            idPesananField.setEditable(false);
            namaPemesanField.setEditable(false);
            totalTagihanField.setEditable(false);
            sisaBayarField.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateStatusLabel = new javax.swing.JLabel();
        idPesanan = new javax.swing.JLabel();
        pemesanLabel = new javax.swing.JLabel();
        totalTagihanLabel = new javax.swing.JLabel();
        pembayaranLabel = new javax.swing.JLabel();
        dibayarLabel = new javax.swing.JLabel();
        sisaBayarLabel = new javax.swing.JLabel();
        statusPesananLabel = new javax.swing.JLabel();
        statusPesanan = new javax.swing.JComboBox<>();
        simpanUpdateBtn = new javax.swing.JButton();
        idPesananField = new javax.swing.JTextField();
        namaPemesanField = new javax.swing.JTextField();
        totalTagihanField = new javax.swing.JTextField();
        dpDiabayarField = new javax.swing.JTextField();
        sisaBayarField = new javax.swing.JTextField();
        tutupJDialogBtn = new javax.swing.JButton();
        copyright5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 154, 124));

        updateStatusLabel.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        updateStatusLabel.setForeground(new java.awt.Color(76, 61, 25));
        updateStatusLabel.setText("Update Status Pembayaran");

        idPesanan.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        idPesanan.setForeground(new java.awt.Color(76, 61, 25));
        idPesanan.setText("ID Pesanan     :");

        pemesanLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        pemesanLabel.setForeground(new java.awt.Color(76, 61, 25));
        pemesanLabel.setText("Pemesan :");

        totalTagihanLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalTagihanLabel.setForeground(new java.awt.Color(76, 61, 25));
        totalTagihanLabel.setText("Total Tagihan :  Rp. ");

        pembayaranLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        pembayaranLabel.setForeground(new java.awt.Color(76, 61, 25));
        pembayaranLabel.setText("Pembayaran   :");

        dibayarLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        dibayarLabel.setForeground(new java.awt.Color(76, 61, 25));
        dibayarLabel.setText("Dibayar          :  Rp. ");

        sisaBayarLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        sisaBayarLabel.setForeground(new java.awt.Color(76, 61, 25));
        sisaBayarLabel.setText("Sisa bayar       :  Rp.");

        statusPesananLabel.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        statusPesananLabel.setForeground(new java.awt.Color(76, 61, 25));
        statusPesananLabel.setText("Status Pesanan :");

        statusPesanan.setBackground(new java.awt.Color(229, 215, 196));
        statusPesanan.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        statusPesanan.setForeground(new java.awt.Color(76, 61, 25));
        statusPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu DP", "Diproses", "Selesai", "Batal" }));

        simpanUpdateBtn.setBackground(new java.awt.Color(53, 64, 36));
        simpanUpdateBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        simpanUpdateBtn.setForeground(new java.awt.Color(229, 215, 196));
        simpanUpdateBtn.setText("Simpan perubahan");
        simpanUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanUpdateBtnActionPerformed(evt);
            }
        });

        idPesananField.setBackground(new java.awt.Color(162, 154, 124));
        idPesananField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        idPesananField.setForeground(new java.awt.Color(76, 61, 25));

        namaPemesanField.setBackground(new java.awt.Color(162, 154, 124));
        namaPemesanField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        namaPemesanField.setForeground(new java.awt.Color(76, 61, 25));

        totalTagihanField.setBackground(new java.awt.Color(162, 154, 124));
        totalTagihanField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalTagihanField.setForeground(new java.awt.Color(76, 61, 25));

        dpDiabayarField.setBackground(new java.awt.Color(162, 154, 124));
        dpDiabayarField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        dpDiabayarField.setForeground(new java.awt.Color(76, 61, 25));
        dpDiabayarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDiabayarFieldActionPerformed(evt);
            }
        });
        dpDiabayarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dpDiabayarFieldKeyReleased(evt);
            }
        });

        sisaBayarField.setBackground(new java.awt.Color(162, 154, 124));
        sisaBayarField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        sisaBayarField.setForeground(new java.awt.Color(76, 61, 25));
        sisaBayarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisaBayarFieldActionPerformed(evt);
            }
        });

        tutupJDialogBtn.setBackground(new java.awt.Color(53, 64, 36));
        tutupJDialogBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tutupJDialogBtn.setForeground(new java.awt.Color(229, 215, 196));
        tutupJDialogBtn.setText("Tutup");
        tutupJDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupJDialogBtnActionPerformed(evt);
            }
        });

        copyright5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        copyright5.setForeground(new java.awt.Color(76, 61, 25));
        copyright5.setText("Copyright : Raynard - 240028 / Nena - 240034 / Darren - 240052");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(copyright5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tutupJDialogBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pembayaranLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statusPesananLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusPesanan, 0, 133, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(idPesanan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(totalTagihanLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalTagihanField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(updateStatusLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sisaBayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dibayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dpDiabayarField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(sisaBayarField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pemesanLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(simpanUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(updateStatusLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPesanan)
                    .addComponent(idPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemesanLabel)
                    .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTagihanLabel)
                    .addComponent(totalTagihanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pembayaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dibayarLabel)
                    .addComponent(dpDiabayarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisaBayarLabel)
                    .addComponent(sisaBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPesananLabel)
                    .addComponent(statusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanUpdateBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutupJDialogBtn)
                    .addComponent(copyright5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpDiabayarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDiabayarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpDiabayarFieldActionPerformed

    private void simpanUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int dpBaru = Integer.parseInt(dpDiabayarField.getText());
            int sisaBaru = totalHarga - dpBaru;
            String statusBaru = statusPesanan.getSelectedItem().toString();
            
            Model.Pesanan p = new Model.Pesanan();
            p.setIdPesanan(currentIdPesanan);

            if (p.updateStatusPembayaran(dpBaru, sisaBaru, statusBaru)) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal update data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "DP harus angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tutupJDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void dpDiabayarFieldKeyReleased(java.awt.event.KeyEvent evt) {
        try {
            String text = dpDiabayarField.getText();
            
            if (!text.isEmpty()) {
                int dp = Integer.parseInt(text);
                int sisa = totalHarga - dp; // hitung sisa otomatis
                sisaBayarField.setText(String.valueOf(sisa));
            } else {
                sisaBayarField.setText(String.valueOf(totalHarga));
            }
        } catch (NumberFormatException e) {
        }
    }

    private void sisaBayarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisaBayarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisaBayarFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyright5;
    private javax.swing.JLabel dibayarLabel;
    private javax.swing.JTextField dpDiabayarField;
    private javax.swing.JLabel idPesanan;
    private javax.swing.JTextField idPesananField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaPemesanField;
    private javax.swing.JLabel pembayaranLabel;
    private javax.swing.JLabel pemesanLabel;
    private javax.swing.JButton simpanUpdateBtn;
    private javax.swing.JTextField sisaBayarField;
    private javax.swing.JLabel sisaBayarLabel;
    private javax.swing.JComboBox<String> statusPesanan;
    private javax.swing.JLabel statusPesananLabel;
    private javax.swing.JTextField totalTagihanField;
    private javax.swing.JLabel totalTagihanLabel;
    private javax.swing.JButton tutupJDialogBtn;
    private javax.swing.JLabel updateStatusLabel;
    // End of variables declaration//GEN-END:variables
}
