/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import Auth.DatabaseConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nenap
 */
public class UpdateStatusBayarJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateStatusBayarJDialog.class.getName());
    
    private int currentIdPesanan;
    private int totalHarga = 0;
    
    /**
     * Creates new form UpdateStatusBayarJDialog
     */
    public UpdateStatusBayarJDialog(java.awt.Frame parent, boolean modal, int idPesanan) {
        super(parent, modal);
        initComponents();
        this.currentIdPesanan = idPesanan;
        loadData();
        setLocationRelativeTo(null);
    }
    
    private void loadData() {
        String sql = "SELECT p.*, u.nama FROM pesanan p JOIN users u ON p.id_user = u.id_user WHERE id_pesanan = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            
            pst.setInt(1, currentIdPesanan);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                idPesananField.setText(String.valueOf(rs.getInt("id_pesanan")));
                namaPemesanField.setText(rs.getString("nama"));
                
                totalHarga = rs.getInt("total_harga");
                int dp = rs.getInt("dp_dibayar");
                int sisa = rs.getInt("sisa_bayar");
                
                totalTagihanField.setText(String.valueOf(totalHarga));
                dpDiabayarField.setText(String.valueOf(dp));
                sisaBayarField.setText(String.valueOf(sisa));
                
                statusPesanan.setSelectedItem(rs.getString("status_pesanan"));
                
                // Field ID dan Nama read-only
                idPesananField.setEditable(false);
                namaPemesanField.setEditable(false);
                totalTagihanField.setEditable(false);
                sisaBayarField.setEditable(false);
            }
        } catch (Exception e) { e.printStackTrace(); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statusPesanan = new javax.swing.JComboBox<>();
        simpanUpdateBtn = new javax.swing.JButton();
        idPesananField = new javax.swing.JTextField();
        namaPemesanField = new javax.swing.JTextField();
        totalTagihanField = new javax.swing.JTextField();
        dpDiabayarField = new javax.swing.JTextField();
        sisaBayarField = new javax.swing.JTextField();
        tutupJDialogBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 154, 124));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 61, 25));
        jLabel1.setText("Update Status Pembayaran");

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 61, 25));
        jLabel2.setText("ID Pesanan :");

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 61, 25));
        jLabel3.setText("Pemesan :");

        jLabel4.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 61, 25));
        jLabel4.setText("Total Tagihan : Rp. ");

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 61, 25));
        jLabel5.setText("Pembayaran :");

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 61, 25));
        jLabel6.setText("Dp dibayar   : Rp. ");

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 61, 25));
        jLabel7.setText("Sisa bayar     : Rp.");

        jLabel8.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 61, 25));
        jLabel8.setText("Status Pesanan :");

        statusPesanan.setBackground(new java.awt.Color(229, 215, 196));
        statusPesanan.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        statusPesanan.setForeground(new java.awt.Color(76, 61, 25));
        statusPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu DP", "Diproses", "Selesai", "Batal" }));

        simpanUpdateBtn.setBackground(new java.awt.Color(53, 64, 36));
        simpanUpdateBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        simpanUpdateBtn.setForeground(new java.awt.Color(229, 215, 196));
        simpanUpdateBtn.setText("Simpan perubahan");
        simpanUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanUpdateBtnActionPerformed(evt);
            }
        });

        idPesananField.setBackground(new java.awt.Color(162, 154, 124));
        idPesananField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        idPesananField.setForeground(new java.awt.Color(76, 61, 25));

        namaPemesanField.setBackground(new java.awt.Color(162, 154, 124));
        namaPemesanField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        namaPemesanField.setForeground(new java.awt.Color(76, 61, 25));

        totalTagihanField.setBackground(new java.awt.Color(162, 154, 124));
        totalTagihanField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        totalTagihanField.setForeground(new java.awt.Color(76, 61, 25));

        dpDiabayarField.setBackground(new java.awt.Color(162, 154, 124));
        dpDiabayarField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        dpDiabayarField.setForeground(new java.awt.Color(76, 61, 25));
        dpDiabayarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDiabayarFieldActionPerformed(evt);
            }
        });
        dpDiabayarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dpDiabayarFieldKeyReleased(evt);
            }
        });

        sisaBayarField.setBackground(new java.awt.Color(162, 154, 124));
        sisaBayarField.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        sisaBayarField.setForeground(new java.awt.Color(76, 61, 25));

        tutupJDialogBtn.setBackground(new java.awt.Color(53, 64, 36));
        tutupJDialogBtn.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        tutupJDialogBtn.setForeground(new java.awt.Color(229, 215, 196));
        tutupJDialogBtn.setText("Tutup");
        tutupJDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupJDialogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tutupJDialogBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalTagihanField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dpDiabayarField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sisaBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(simpanUpdateBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(idPesananField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalTagihanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dpDiabayarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(statusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanUpdateBtn)))
                    .addComponent(sisaBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tutupJDialogBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpDiabayarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDiabayarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpDiabayarFieldActionPerformed

    private void simpanUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanUpdateBtnActionPerformed
        try {
            // 1. Ambil data baru
            int dpBaru = Integer.parseInt(dpDiabayarField.getText());
            int sisaBaru = totalHarga - dpBaru;
            String statusBaru = statusPesanan.getSelectedItem().toString();
            
            // 2. Update Database
            String sql = "UPDATE pesanan SET dp_dibayar=?, sisa_bayar=?, status_pesanan=? WHERE id_pesanan=?";
            Connection conn = DatabaseConnection.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setInt(1, dpBaru);
            pst.setInt(2, sisaBaru);
            pst.setString(3, statusBaru);
            pst.setInt(4, currentIdPesanan);
            
            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
                this.dispose(); // Tutup dialog
            } else {
                JOptionPane.showMessageDialog(this, "Gagal update.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "DP harus angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_simpanUpdateBtnActionPerformed

    private void tutupJDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupJDialogBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_tutupJDialogBtnActionPerformed

    private void dpDiabayarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpDiabayarFieldKeyReleased
        try {
            // Ambil angka yang baru diketik
            String text = dpDiabayarField.getText();
            
            if (!text.isEmpty()) {
                int dp = Integer.parseInt(text);
                int sisa = totalHarga - dp; // Hitung sisa otomatis
                sisaBayarField.setText(String.valueOf(sisa));
            } else {
                // Jika dihapus kosong, kembalikan ke total harga asli
                sisaBayarField.setText(String.valueOf(totalHarga));
            }
        } catch (NumberFormatException e) {
            // Abaikan jika user mengetik huruf
        }
    }//GEN-LAST:event_dpDiabayarFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dpDiabayarField;
    private javax.swing.JTextField idPesananField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaPemesanField;
    private javax.swing.JButton simpanUpdateBtn;
    private javax.swing.JTextField sisaBayarField;
    private javax.swing.JComboBox<String> statusPesanan;
    private javax.swing.JTextField totalTagihanField;
    private javax.swing.JButton tutupJDialogBtn;
    // End of variables declaration//GEN-END:variables
}
